### ISSUE TITLE
Documentation links dead

### ISSUE THREAD

**Issue by zacharyhamm** [ember-cli-deploy/ember-cli-deploy-slack#14]
The README tells us that if we want to know in detail how to configure ember-cli-deploy plugins like the slack plugin, we should go to [http://ember-cli.github.io/ember-cli-deploy/plugins](http://ember-cli.github.io/ember-cli-deploy/plugins). This link is dead, and the closest equivalent I can find is here: [http://ember-cli-deploy.github.io/ember-cli-deploy/docs/v0.6.x/plugins-overview/](http://ember-cli-deploy.github.io/ember-cli-deploy/docs/v0.6.x/plugins-overview/) but it doesn't seem to be the "detailed documentation" suggested in the README.md.

**Comment by ghedamat** [comment]
@imipolexg you are  correct, the repository has been transferred outside the "ember-cli" organization and we haven't updated all the link yet.

if you have time for a quick PR it would be much appreciated.

please prefix your commit with `[DOC]`
i.e `[DOC] fixed broken links`

thanks a lot!

**Comment by ghedamat** [comment]
also I believe http://ember-cli-deploy.github.io/ember-cli-deploy/docs/v0.6.x/configuration-overview/ would probably be the right link?
