### ISSUE TITLE
"didFail" hook is not working

### ISSUE THREAD

**Issue by pablogravielseo** [ember-cli-deploy/ember-cli-deploy-slack#22]
Hi guys, I've created a custom "willDeploy", "didDeploy" and "didFail" hooks, "willDeploy" hook and "didDeploy" hook works, but the "didFail" hook isn't working for me when the CI got an error, anyone faced something similar?

**Comment by achambers** [comment]
Hi. Any chance you can point us to some plugin code so I can try and help debug it?

**Comment by pablogravielseo** [comment]
Hi Aaron, thank you for your help, initially we tried to use the "default didFail" hook, but this doesn't works, so I've created the custom "didFail" hooks that is identical to the default, but doesn't works.

**Comment by pablogravielseo** [comment]
@achambers I thought the "didFail" hook would fire when the CI tests didn't pass. Thank you for your help.

**Comment by achambers** [comment]
@pablogravielseo Nope. `didFail` fires when an error is experienced during the deployment pipeline. It doesn't know anything about the rest of your CI.

I'm going to close this for now. If I've missed something or you have any other questions, feel free to re-open this issue or create a new one.

**Comment by pablogravielseo** [comment]
Thank you for the clarification @achambers.
